//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_commerce_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestMonials
    {
        public long ID { get; set; }
        public string Image { get; set; }
        public string FeedBack { get; set; }
        public Nullable<bool> IsConfirm { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public string UpdateDate { get; set; }
        public long UserFK { get; set; }
    }
}
